-- VIMET — el staff sube sus propios ejercicios (GIF propio) a la biblioteca,
-- además del catálogo seedeado desde exercises-dataset (0012).

alter table public.ejercicios add column if not exists origen text not null default 'dataset';
alter table public.ejercicios add constraint ejercicios_origen_check check (origen in ('dataset', 'staff'));

alter table public.ejercicios add column if not exists creado_por uuid references auth.users(id) on delete set null;

-- Los ids del seed son manuales (del dataset externo). Para que el staff pueda
-- insertar sin id explícito, la columna pasa a identity "by default" arrancando
-- muy por encima del rango del dataset (no colisiona) — el seed sigue pudiendo
-- pisar un id explícito porque es BY DEFAULT, no ALWAYS.
alter table public.ejercicios alter column id add generated by default as identity (start with 1000000);

create index if not exists ejercicios_origen_idx on public.ejercicios(origen);
